### PR TITLE
typo in udev file name

### PR DESCRIPTION
**Pull request by snowdd1**
rules file was named *70-kndx.rules* instead of **70-knxd.rules** (as mentioned in readme)

### CODE REVIEW

**Comment by snowdd1** [comment]
I do not understand why the travis check is failing with that change!

**Comment by smurfix** [comment]
On 12.03.2016 11:32, Raoul wrote:
>
> I do not understand why the travis check is failing with that change!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/knxd/knxd/pull/129#issuecomment-195712168>.
>
It probably failed before. Will check.

-- 
-- Matthias Urlichs

**Comment by tru7** [comment]
I get the same error when running configure, it ends with:

checking for systemd/sd-daemon.h... no
./configure: line 16888: syntax error near unexpected token `<<<'
./configure: line 16888: `<<<<<<< HEAD'

**Comment by smurfix** [comment]
On 12.03.2016 14:50, Othmar Truniger wrote:
>
> I get the same error when running configure, it ends with:
>
> checking for systemd/sd-daemon.h... no
> ./configure: line 16888: syntax error near unexpected token |<<<'
> ./configure: line 16888:|<<<<<<< HEAD'
>
>
Bah. That was a botched merge commit.

Please do
$ git fetch origin
$ git reset --hard origin/master

and rebuild.

Sorry about that.

-- 
-- Matthias Urlichs

**Comment by tru7** [comment]
That does not help, it's already on origin/master

**Comment by smurfix** [comment]
On 12.03.2016 15:14, Othmar Truniger wrote:
>
> That does not help, it's already on origin/master
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/knxd/knxd/pull/129#issuecomment-195748779>.
>
Sure it does. I just force-pushed the correct version. Travis now
reports OK.

-- 
-- Matthias Urlichs

**Comment by smurfix** [comment]
Fixed

**Pull request closed without merging**
