### PR TITLE
WIP/RFC: add systemd support

### PR DESCRIPTION
**Pull request by marcecj**
This series of commits adds thorough (but *optional* and *off by default*) systemd support.  I do not intend to have this pull request merged (messy commit history, open questions, etc.), but wanted to get some feedback on it (hence the lack of a `Signed-off-by` line).

My plan is to create a new branch with a clean commit history (and without the `wip_` prefix) once everybody is happy with my changes and then open a proper pull request for that.

### Source Code Changes

I wrote a simple `SystemdServer` class (following `InetServer` and `LocalServer`) that accepts a file descriptor on which it then listens.  Support for multiple sockets is implemented by looping over the fds passed by systemd and creating one `SystemdServer` instance for each.  If even one of them is not of the right type, the process `die()`s.  In `knxd.cpp`, I modified the behaviour to the following:
- Do *not* `die()` when no listen address is given (neither `-u`, `-i` or `-S` were passed on the command line), but instead listen to whatever sockets systemd provided (and if that fails, `die()`).
- Conversely, only listen on systemd provided sockets when neither `-u` or `-i` were provided (should I add `-S`, too?).

I think that the `SystemdServer` class could hypothetically be reused for systems similar to systemd, such as launchd (which might be relevant for BSD systems).

### Build System Changes

Well, I have practically no clue on autoconf, so I hope it's not completely disastrous.   All of the modifications and additions are mine, except for most of the code in `m4/`, which I copied over from https://github.com/mcgrof/funk-systemd/.  I did modify `m4/systemd.m4` to support newer systemd versions that don't have libsystemd-daemon anymore, along with some other smaller things (hence my copyright line; I really should open a separate pull request for that).

(This definitely would have been more pleasant with CMake.)

### Current Status

I think systemd support is complete:
- Supports socket activation (but should work without).
- Includes a sysusers.d configuration file for automatically creating the knxd user and group.  This way you can start knxd as a reqular user (requires very new systemd though, in fact, newer than I have on my systems).
- Includes an environment file that installs into `${prefix}/etc/` for passing options to knxd (included by the service unit).

By default, you would run `systemctl enable knxd.service`, which also enables `knxd.socket`. When starting the service unit manually, make sure to start the socket unit first.

### Testing

I haven't thoroughly tested this, but have tried the following:
- building with and without `--enable-systemd` (seems to behave correctly)
- starting the socket and service units (seems to work)

I tested an older version at work yesterday (where I have access to KNX hardware and client software), which appeared to work correctly (including socket activation), but I would obviously like other people to test my patch, too.

### Questions

- Are the copyright lines OK?
- Is the build system support OK, or should it be simplified?  Is that even important, since you want to switch to CMake anyway?
- Can somebody with autoconf experience please tell me whether the `AX_LOCAL_EXPAND_CONFIG` macro is even necessary?
- Can you think of better defaults for the systemd units?

### CODE REVIEW

**Comment by marcecj** [comment]
Just a quick comment: I have since installed KNXD with this set of changes on an RPi 2B running Pidora 21 (which uses systemd-216, IIRC), and it appears to work fine.  Again, it hasn't been used extensively (yet), but seems to behave as expected.

**Comment by smurfix** [comment]
I'd like to just merge this; the patches seem non-intrusive enough.

Any progress on the CMake switch?

**Comment by Makki1** [comment]
I cannot fully judge this but it seems ok to me.
CMake: I dont see any priority on this, as it will first of all break many things, so why not stay with automake for now, it's working.

**Comment by marcecj** [comment]
Well, since people seem to agree that what I did is OK, I'll create a new branch, rebase, and open a new pull request with a nicer history (and signed-off-by lines).  Does that sound OK, or should I wait for more comments?

My own take on CMake vs. autotools: I prefer CMake, though I don't actually *like* either of the two.  However, I dislike autotools a tiny bit less after working on this PR.

**Comment by smurfix** [comment]
On 22.05.2015 15:50, Marc Joliet wrote:
>
> Well, since people seem to agree that what I did is OK, I'll create a
> new branch, rebase, and open a new pull request with a nicer history
> (and signed-off-by lines). Does that sound OK, or should I wait for
> more comments?
>
Actually I already had a close look at your branch's commit history,
thought it's clean enough, and went ahead and merged it.

Dunno about everybody else, but I'd rather focus on getting features
(and bug fixes and code clean-up and …) into the source than having
"clean" history.

-- 
-- Matthias Urlichs

**Comment by marcecj** [comment]
Hey, if you're fine with it, then I'm fine with it!  Feel free to merge this PR, then.

**Comment by RichiH** [comment]
Merging from the bathtub on my phone. We do live in the future....

**Pull request merged**
