### PR TITLE
create version from debian/changelog

### PR DESCRIPTION
**Pull request by tru7**
Signed-off-by: Othmar Truniger github@truniger.ch

Don't know if this is really a good idea but works for me at least. Feel free to improve the version.sh script.

### CODE REVIEW

**Comment by smurfix** [comment]
On 13.03.2016 17:56, Othmar Truniger wrote:
>
> Signed-off-by: Othmar Truniger github@truniger.ch
> <mailto:github@truniger.ch>
>
> Don't know if this is really a good idea but works for me at least.
> Feel free to improve the version.sh script.
>
OK, except that you can replace the grep/head/awk/tr chain with a single
sed command.

sed -ne '/^knx/{s/.*(\(.*\)\(-.*\)).*/\1/p;q;}' <../knxd/debian/changelog

-- 
-- Matthias Urlichs

**Comment by tru7** [comment]
I was convinced that there is better way beyond my horizon. You may drop my pull request and fix it yourself if you like the idea. I like the single sed command, but I wonder about your pathname and I also see you omit the version part with the dash.

**Comment by smurfix** [comment]
On 14.03.2016 10:18, Othmar Truniger wrote:
>
> I was convinced that there is better way beyond my horizon. You may
> drop my pull request and fix it yourself if you like the idea. I like
> the single sed command, but I wonder about your pathname and I also
> see you omit the version part with the dash.
>
The pathname is probably a copy/paste error. The part after the dash is
intentional because that it is supposed to be just packaging, thus not
relevant for the version of knxd itself, but I might keep it anyway.

-- 
-- Matthias Urlichs

**Comment by tru7** [comment]
Done independently from this pull request

**Pull request closed without merging**
