### PR TITLE
build on macOS

### PR DESCRIPTION
**Pull request by mike-kfed**
There is one more thing needed, but not sure how to make that OS independent: The linker on macOS does not support `--whole-archive` or `--no-whole-archive` - I don't know why those options are in use for the server code in the first place, maybe this can be removed for all OS? What's an acceptable way to modify .am files based on environment? Anyways this patch would be required to make it compile on macOS:

```diff
diff --git a/src/server/Makefile.am b/src/server/Makefile.am
index c51f98e..5fbf3de 100644
--- a/src/server/Makefile.am
+++ b/src/server/Makefile.am
@@ -3,7 +3,7 @@ libexec_PROGRAMS = knxd_args

 AM_CPPFLAGS=-I$(top_srcdir)/src/libserver -I$(top_srcdir)/src/backend -I$(top_srcdir)/src/common -I$(top_srcdir)/src/usb $(LIBUSB_CFLAGS) $(SYSTEMD_CFLAGS) -Wno-missing-field-initializers
 knxd_CPPFLAGS=$(AM_CPPFLAGS) -DLIBEXECDIR="\"$(libexecdir)\""
-knxd_LDFLAGS=-Wl,--whole-archive,../backend/libbackend.a,../libserver/libserver.a,--no-whole-archive
+knxd_LDFLAGS=-Wl,../backend/libbackend.a,../libserver/libserver.a
 knxd_LDADD=../libserver/libeibstack.a ../common/libcommon.a ../usb/libusb.a $(LIBUSB_LIBS) $(SYSTEMD_LIBS) $(EV_LIBS)
 knxd_DEPENDENCIES=../libserver/libserver.a ../backend/libbackend.a ../libserver/libeibstack.a ../common/libcommon.a ../usb/libusb.a
 knxd_args_DEPENDENCIES=../common/libcommon.a
```

### CODE REVIEW

**Comment by smurfix** [comment]
That `server/Makefile.am` patch wouldn't work on Linux, but apparently it's now possible to simply reorder the libraries. See current master.

**Comment by smurfix** [comment]
… well, it's possible to link that way, but the result doesn't work. Owch.

**Comment by smurfix** [comment]
So how do you teach macOS linker how to add code that's not referenced and only "install" itself into a binary by way of constructor side effects? because that's what happens here. If you build without --whole-library the result should have no filters, drivers or servers. (`knxd -l filter`)

**Comment by mike-kfed** [comment]
you are correct `./src/server/knxd -l filter` is empty, so building on macOS works (just used current master) but that feature is broken. should I create an Issue with this, maybe someone else can help, or I pick it up later when I am done with my FreeBSD project (the compileability on macOS was just a sideeffect of this work)

**Comment by smurfix** [comment]
I assume that macOS has some other way to do that, or else use GNU ld?

A new issue for it makes sense.

**Pull request merged**
