### PR TITLE
Update usbif.cpp

### PR DESCRIPTION
**Pull request by StalderT**
fix for https://github.com/knxd/knxd/issues/102 and probably https://github.com/knxd/knxd/issues/100

### CODE REVIEW

**Comment by smurfix** [comment]
That change results in a busy-looping knxd, which arguably is an improvement wrt one that doesn't work at all; however, the correct fix is to add a listener to the right file descriptor. (Or, if that should turn out not to be possible for whatever reason, poll the interface a configurable number of times per second. Not in a tight loop.)

I don't own such an interface (the idea of using USB-HID to talk to KNX is broken by design) and thus can't debug this further.

**Comment by smurfix** [comment]
NB: Did the old eibd handle this correctly? (I.e., without busy looping)

**Comment by StalderT** [comment]
Hello,

Thanks for your reply.

I can't test old eibd because I have a segfault and cEMI patch don't compile.

Do you really think that the problem comes from there?

Perhaps rather something like this (the busy-looping came after receiving first telegram) : 

https://github.com/knxd/knxd/compare/master...StalderT:patch-2

I would try it Monday

**Comment by smurfix** [comment]
On 14.11.2015 15:34, StalderT wrote:
>
> Perhaps rather something like this (the busy-looping came after
> receiving first telegram) :
>
> master...StalderT:patch-2
> <https://github.com/knxd/knxd/compare/master...StalderT:patch-2>
>
> I would try it Monday
>
That looks like it'd make sense to test. Thanks for investigating.

-- 
-- Matthias Urlichs

**Comment by StalderT** [comment]
I have test the patch. No more busy-looping / 100% CPU. USB Interface works. Programming works.
I have made a new complete PR : https://github.com/knxd/knxd/pull/105 you can merge the new one and delete this PR.

Bests regards,

Thomas

**Comment by smurfix** [comment]
Superseded by #105

**Pull request closed without merging**
