### PR TITLE
increased default timeout and retry count for older usb interfaces

### PR DESCRIPTION
**Pull request by ersingencturk**
my usb/knx interface sends data and confirmation callback slower then timeout , this is the fix

### CODE REVIEW

**Comment by smurfix** [comment]
Umm, really? 6 seconds for timeout? that seems a bit on the high side. Can you narrow the required range down a bit?

The other problem with this change is that it masks the real problem – knxd should not go belly-up with this error, no matter what the USB device does.

**Comment by ersingencturk** [comment]
I started trying from lower values like 600ms , 1sec and etc. and all i was sending simple groupwrites. 1 sec is barely on the level (it might be my old device though) so just to be on the safe side I increased the value. I think rest of the code is ok but a bit messed up. normally async code seems working, but the timeout interrupts it before it does it's magic. as long as your asnc code works timeout should be fine even though its a bit on the high side.

**Comment by ersingencturk** [comment]
I think this means whenever a usb device won't respond it will give feedback and fail to error after 6secs x 5 times = 30 secs to which is fair enough for me. If the device don't return response until this time yeah it's an error. however making it force to return in 300msec for a respond is a bit overkill. I don't see any disadvantage of setting this high

**Comment by steinradler** [comment]
Hi, where is the patch to apply, if I didn´t selected it during the script?

`root@raspberrypi:/etc/systemd/system/multi-user.target.wants# knxd -V
knxd 0.14.25
root@raspberrypi:/etc/systemd/system/multi-user.target.wants# cat knxd.service
[Unit]
Description=KNX Daemon
After=network.target

[Service]
EnvironmentFile=/etc/default/knxd
# Wait for all interfaces, systemd-networkd-wait-online.service must be enabled
#ExecStartPre=/lib/systemd/systemd-networkd-wait-online --timeout=60
# Wait for a specific interface
#ExecStartPre=/lib/systemd/systemd-networkd-wait-online --timeout=60 --interface=eth0
ExecStart=/usr/local/bin/knxd -p /run/knxd/knxd.pid $KNXD_OPTIONS
Type=forking
PIDFile=/run/knxd/knxd.pid
User=knxd
Group=knxd
#TimeoutStartSec=60

[Install]
WantedBy=multi-user.target network-online.target
root@raspberrypi:/etc/systemd/system/multi-user.target.wants#
`

Which file I have to edit, or is it necessary to  run 'install_knxd_systemd.sh' again.

Thank you for your answers!

**Comment by steinradler** [comment]
Hi, it seems to be working now!

I was rerunning the script and decided for the patch and changed afterwards my starting params.
No my first test are all successfull.

Cheers!

**Comment by smurfix** [comment]
Timeout incremented in 0.14.33.

**Pull request closed without merging**
