### PR TITLE
Make sure we indicate success on disconnect

### PR DESCRIPTION
**Pull request by elupus**
* Signal success on disconnects to ETS5
* Signal disconnection of busmon/groupmon to ETS5 on knxd shutdown (note, fails in NAT mode since apperently ETS5 only accepts data originating from the multicast socket)
* Signal tunnel requests/config request ack back to client from same socket as request

### CODE REVIEW

**Comment by elupus** [comment]
Turned out to be somewhat more complicated than initial try since the request wasn't really performed fully internally. Update patch (one issue remaining is that we now send a disconnect_request when the disconnect was really already requested)

**Comment by elupus** [comment]
Note. i might have introduce a segmentation fault on shutdown of knxd with the fixes for connstate destruction.

**Comment by smurfix** [comment]
Is this request now complete?

**Comment by elupus** [comment]
i'm trying to track down a segfault on ctrl+c. something about how the Thread's get destroyed. I'm not sure it's new for this pull thou

**Comment by elupus** [comment]
There we go. tracked it down.

**Comment by elupus** [comment]
This is good to go.

There is one trailing issue with the originating socket for tunnel/config requests that i could add here to if you want. I'm just not happy with the solution:

```
diff --git a/src/libserver/eibnetserver.cpp b/src/libserver/eibnetserver.cpp
index ea983ad..801a024 100644
--- a/src/libserver/eibnetserver.cpp
+++ b/src/libserver/eibnetserver.cpp
@@ -435,7 +435,10 @@ ConnState::Run (pth_sem_t * stop1)
                   p = r.ToPacket ();
                 }
               reset_time(sendtimeout, 1, 0);
-              parent->mcast->Send (p, daddr);
+              if (nat)
+                parent->mcast->Send (p, daddr);
+              else
+                parent->Send (p, daddr);
             }
         }
     }
@@ -448,7 +451,10 @@ ConnState::Run (pth_sem_t * stop1)
         {
           r.caddr.sin_port = parent->Port;
           r.nat = nat;
-          parent->Send (r.ToPacket (), caddr);
+          if (nat)
+            parent->mcast->Send (r.ToPacket (), caddr);
+          else
+            parent->Send (r.ToPacket (), caddr);
         }
     }
   parent->drop_state (std::static_pointer_cast<ConnState>(shared_from_this()));
```

The problem being that ETS5 expects the X.con packet to originate from the socket that it sent it's X.ind to. But ConnState have no access to this originating socket. Above is a hack to make this just depend on nat state, which sort of works (until i start in nat mode directly to the server port).

The alternative would be to extend the queue so it contains the socket to originate from too.

**Pull request merged**
