### PR TITLE
Updated Archlinux package-build

### PR DESCRIPTION
**Pull request by cjk**
added missing cmake dependency, improve on formatting.

### CODE REVIEW

**Comment by mike-kfed** [comment]
As I am playing with building knxd on BSD I guess this is the reason for cmake sneaking in: `./tools/get_libfmt: cmake: not found` - if you run configure and libfmt is missing, it needs it

**Comment by cjk** [comment]
@mike-kfed Yes, that was the reason. Do you think it would be better to require libfmt instead?

**Comment by smurfix** [comment]
The download-libfmt-and-cmake workaround was put in for installation on routers and similar systems whose native packaging system doesn't have a native, recent-enough libfmt. For anything else, using the libfmt that's package in the OS/distribution is by far the superior option.

**Comment by cjk** [comment]
Alright, so out goes `cmake` and `fmt` is now in build-dependencies.

**Pull request merged**
