### PR TITLE
RPM Build

### PR DESCRIPTION
**Pull request by jsauermann**
1. I have added a directory rpm where the RPM build takes place.

RPMs can be built by a new make target called RPM at the top level. This target
works only if a tar file is present in the top-level directory (and complains otherwise),

2. I also added a 'make help' target to the top level Makefile showing non-standard targets like RPM.

The "normal" build failed on my Linux Mint because -latomic was missing. I added a check
for the presence of libatomic.a which should fix this.

### CODE REVIEW

**Comment by smurfix** [comment]
Why do you add the automake files to the repository?
The RPM build should be able to run bootstrap.sh.
Also, those files do need updates on newer or uncommon systems, thus I'd like to use the system's copy.

**Comment by jsauermann** [comment]
Hi Matthias,

I can remove them. I normally put all the files generated by 
autoconf/automake into the repository
so that I can check-out the code from a build system that does not have 
automake/conf installed.
Normally ./configure itself suffices for that purpose, but it is listed 
in .gitignore so that git complains
when adding it.

We can't run bootstrap.sh from the RPM build because the RPM build is 
called from Makefile which
does not exist at that point in time.

So the RPM build will look like this then:

     ./bootstrap.sh
     ./configure
     make RPM

BTW, my own workcycle looks like this (and that required the files that 
I added to the repository):

     autoreconf
     ./configure
     make ...

**Comment by jsauermann** [comment]
Hi,

I believe i found the problem with make clean and friends

It was caused by the rule

       gen/%.c : Makefile

in src/client/c/Makefile.am

When you run ./configure a second time, then Makefile is updated and
hence the .c files in gen/ are recreated and then recompiled (which then 
failed
for unknown reasons - probably called from the wrong directory) The idea of
the rule was maybe to recompile when new files are added to Makefile,
but that was not what it did and I believe it creates more trouble than 
benefits.

The solution is to simply say

       gen/%.c :

With that make clean and friends also work after a second ./configure

I also fixed Makefile.am in the USB directory, removing dependencies on 
two not existing files.
With that, make dist (which is the proper dependency for make RPM) also 
works now.

/// Jürgen

**Comment by jsauermann** [comment]
Signed-off-by: Jürgen Sauermann <juergen.sauermann@t-online.de>

**Comment by smurfix** [comment]
Could you fix the if() test and resubmit?

**Comment by jsauermann** [comment]
Thanks a lot.

**Pull request merged**
