### PR TITLE
Gentoo ebuild fixes

### PR DESCRIPTION
**Pull request by mike-kfed**
found a bug in the ebuilds, also switched to use stable branch instead of the tag. sorry for the extra PR

### CODE REVIEW

**Comment by mike-kfed** [comment]
ahh, now I get it, you "tag" by setting an entry in the `debian/changelog` file / changing `configure.ac`. For the gentoo ebuilds to work an actual `git tag v0.10.14` tag is needed. This tag would then be checked out by portage and the correct release would be built. (or as it is now: the most recent commit on stable branch). I will keep the stable branch solution and will ask gentoo maintainers how this should be versioned then.

**Comment by smurfix** [comment]
On 09.12.2016 17:15, Michael Kefeder wrote:
>
> ahh, now I get it, you "tag" by setting an entry in the
> |debian/changelog| file / changing |configure.ac|. For the gentoo
> ebuilds to work an actual |git tag v0.10.14| tag is needed. This tag
> would then be checked out by portage and the correct release would be
> built. (or as it is now: the most recent commit on stable branch). I
> will keep the stable branch solution and will ask gentoo maintainers
> how this should be versioned then.
>
I did tag the release, I just forgot to push the tag. Fixed.

-- 
-- Matthias Urlichs

**Comment by smurfix** [comment]
Cherry-picked.

Please don't merge trees yourself before submitting a pull request (that's the maintainer's job, unless you have a good reason to).

Also, if you submit changes for gentoo to use the stable branch, why are you checking them into master?

**Comment by mike-kfed** [comment]
Well I had to merge master into my branch to then only have the changes since the last pullrequest, for this additional one. Sorry if that's the wrong way to do it, I will create a new branch next time.

Right now the ebuilds in master are broken, stable branch works fine. Could you please apply the changes to master aswell? I wouldn't expect a gentoo user to use the stable branch to fetch the ebuilds, especially since the README.md in contrib/gentoo doesn't tell them to do it.

**Pull request closed without merging**
