### PR TITLE
Fix compile error for PPCP64.

### PR DESCRIPTION
**Pull request by mfechner**

### CODE REVIEW

**Comment by mfechner** [comment]
Any chance to get this merged?
I have this fix since 2019-07-26 22:23:32 UTC in PRD and it works fine.

**Comment by smurfix** [comment]
Any chance you could respond to my comment?
Specifically, would simply using EAFNOSUPPORT instead of ENODATA work?

**Comment by pkubaj** [comment]
Yes, EAFNOSUPPORT works as well.
Thanks for your work!

**Comment by mfechner** [comment]
Thanks a lot!

**Pull request closed without merging**
