### PR TITLE
compile on FreeBSD

### PR DESCRIPTION
**Pull request by mike-kfed**
Done on FreeBSD 11.2 using clang

Please note that this is just a initial working pull request. Code style and probably much more is not acceptable and I will fix that once I was informed how to do it correctly - here I am just providing a first glimpse on what needs to be done for FreeBSD compile-ability.

Access to KNX hardware for me will be possible from 2nd january onwards, no idea if the compiled stuff works in practice - so if this for some reason is acceptable code, please merge after confirmation of it working with a serial knx-interface.

### CODE REVIEW

**Comment by smurfix** [comment]
Thanks for these patches. However, `__FREEBSD__` and related macros are not acceptable. `configure` needs to discover which MAC address method to use, and it should have discovered the existence of SA_SIZE; please fix that instead of guarding the (re)declaration.
As to the headers: discovering whether they exist and then including them if they do, regardless of whether they're actually required on a particular platform, is generally the best way.

**Comment by smurfix** [comment]
Thanks for these patches. However, `__FREEBSD__` and related macros are not acceptable. `configure` needs to discover which MAC address method to use, and it should have discovered the existence of SA_SIZE; please fix that instead of guarding the (re)declaration.
As to the headers: discovering whether they exist and then including them if they do, regardless of whether they're actually required on a particular platform, is generally the best way.

**Comment by smurfix** [comment]
The bit about `__OS__` macros is documented in the knxd Wiki somewhere. I have added a `CodingStyle` file with some (rudimentary) documentation of this.

**Comment by mike-kfed** [comment]
Before starting with the meaningful implementation I first verified that knxd runs with a TPUART knx-interface on FreeBSD. It does, just a heads up that I am working on this, it's just a slow process, sorry.

**Comment by smurfix** [comment]
Thank you, this looks good :+1: 
Do you think this is ready for merging?

**Comment by mike-kfed** [comment]
this branch compiled successfully on macOS 10.14.2 and linux for me too. So I'd say it is good to go. changes needed for macOS will be another pull request ;)

**Pull request merged**
