### PR TITLE
spec file for opensuse 13 and centos7

### PR DESCRIPTION
**Pull request by mike-kfed**
- please note this really only works for v0.12.16 as Centos7 cannot compile >=knxd-0.14!
- this will be the new basis spec file for master (pull request coming up once I have fedora running)
- please merge into knxd branch v0.12 too

### CODE REVIEW

**Comment by smurfix** [comment]
Umm, 

> please merge into knxd branch v0.12 too

I can't "merge" that to v0.12. Patches flow the other way. Would you mind re-basing your patches onto v0.12 instead?

**Comment by mike-kfed** [comment]
that means a lot of changes, because this is still the old weird knxd.spec.in file with the custom buildroot and stuff... I can remove the makefile, the knxd.spec.in and replace it with the new one if you want. (kind of replaying my changes that made it into master)

**Comment by mike-kfed** [comment]
added a separate pull request that does the needed work for branch v0.12
I guess this thing can now be merged to master, v0.14 and v0.16
I have something that "works" on fedora with v0.14 but this needs further testing, I hope to send the pull request in the coming days.

**Comment by mike-kfed** [comment]
Since v0.12.x was merged separately, I added my changes to build 0.14.15 - worked von Fedora 25 and OpenSUSE Leap 43.2. Wiki has been updated with infos how to do it on those platforms.

**Comment by smurfix** [comment]
You were a bit too fast, I needed to pull v0.12 into v0.14 first.

I have now merged everything up and resolved the conflicts. Please check if anything broke.

**Comment by mike-kfed** [comment]
v0.14 and master branch have the spec file for 0.12.16 now, this means commits  80f6a59 and b4c6248 are missing somehow

**Comment by mike-kfed** [comment]
lots of changes are lost in the spec file, I will create a new pull request

**Comment by smurfix** [comment]
Is there a way to retrieve the version by running `tools/version.sh` instead? I don't like hard-coding the version number.

**Comment by mike-kfed** [comment]
sure, just add replacing of the version number in bootstrap.sh or something similar (at ./configure time it's too late). I actually had that in one of my pull requests getting rid of the knxd.spec.in file iirc.
Reason that it is no longer in there, for - at least redhat based distros - a rpm to be accepted there must be an entry in `%history` part of the specfile with the same version number. Which means just changing the version number is not enough if that ever goes to real-life-release (this can be automated too though, hrhr).

**Comment by mike-kfed** [comment]
having this in bootstrap.sh would enable pretty nice packaging with 

1. download v0.x.x.x.tar.gz
2. unpack && bootstrap
3. pack into knxd-0.x.x.tar.gz
4. rpmbuild -ta knxd-0.x.x.tar.gz
5. profit!

but then again, I see the spec file more as a starting point for whoever will package this. This maintainer will then take care of using proper version numbers and stuff (there could be subreleases that fix packaging bugs only for example). Therefore I wouldn't put too much effort in the automated version number replacement.

**Pull request closed without merging**
